server:
  port: 8081

spring:
  application:
    name: Placement_Engine_Gateway_Service

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: Placement_Engine_Company_Service
          uri: http://localhost:8084
          predicates:
            - Path=/com/**
        - id: Placement_Engine_Registration_Service
          uri: http://localhost:8082
          predicates:
            - Path=/register/**
        - id: Placement_Engine_Authentication_Service
          uri: http://localhost:8080
          predicates:
            - Path=/user/Authentication/**
        - id: Placement_Engine_JobPosting_Service
          uri: http://localhost:8088
          predicates:
            - Path=/JobPosting/byRecruiter/**
            - Path=/Job/apply/**
